---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: use-plugin
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    plugin:
      name: my-plugin-v1.0
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: use-plugin-2
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    plugin:
      name: my-plugin-2-v1.0
